[main]
term=foot

font=Iosevka:size=20:Medium

# ~/.config/foot/foot.ini

[colors]
# Absolute pitch black background and high-contrast white foreground
background=000000
foreground=ffffff

# Normal colors (Matches the exact hex codes from Emacs Modus Vivendi)
regular0=000000  # black
regular1=ff5f59  # red
regular2=44bc44  # green
regular3=d0bc00  # yellow
regular4=2fafff  # blue (Matches your Go strings)
regular5=feacd0  # magenta (Matches your Go functions)
regular6=00d3d0  # cyan (Matches your Go package keywords)
regular7=bfbfbf  # white

# Bright colors
bright0=595959   # bright black (grey)
bright1=ff5f5f   # bright red
bright2=44df44   # bright green
bright3=efef00   # bright yellow
bright4=338fec   # bright blue
bright5=ff66ff   # bright magenta
bright6=00eff0   # bright cyan
bright7=ffffff   # bright white

[mouse]
hide-when-typing=yes
