# 1. Add the leading '/' to make the path absolute
preload = /home/miners/Pictures/Wallpapers/modusVivendi.png

# 2. Use the new object syntax for the wallpaper definition
wallpaper {
    monitor = eDP-1
    path = /home/miners/Pictures/Wallpapers/modusVivendi.png
fit_mode = cover
}

splash = false
ipc = on
